name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11.0.8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      # - name: Deploy to Github Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./dist

      - name: Deploy to FTPS
        id: deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTPS_SERVER }}
          username: ${{ secrets.FTPS_USERNAME }}
          password: ${{ secrets.FTPS_PASSWORD }}
          local-dir: ./dist/
          server-dir: /memory/
        continue-on-error: true

      - name: Retry Deploy to FTPS
        if: steps.deploy.outcome == 'failure'
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTPS_SERVER }}
          username: ${{ secrets.FTPS_USERNAME }}
          password: ${{ secrets.FTPS_PASSWORD }}
          local-dir: ./dist/
          server-dir: /matthias-tausch.com/
